//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MovieLibraryEntities1 : DbContext
    {
        public MovieLibraryEntities1()
            : base("name=MovieLibraryEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_FAVOURITE> TBL_FAVOURITE { get; set; }
        public virtual DbSet<TBL_MOVIE> TBL_MOVIE { get; set; }
        public virtual DbSet<TBL_MOVIEPREVIEW> TBL_MOVIEPREVIEW { get; set; }
        public virtual DbSet<TBL_USER> TBL_USER { get; set; }
        public virtual DbSet<TBL_WATCHLIST> TBL_WATCHLIST { get; set; }
        public virtual DbSet<TBL_WATCHLIST_ELEMENT> TBL_WATCHLIST_ELEMENT { get; set; }
    }
}
