//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_WATCHLIST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_WATCHLIST()
        {
            this.TBL_WATCHLIST_ELEMENT = new HashSet<TBL_WATCHLIST_ELEMENT>();
        }
    
        public short WatchListId { get; set; }
        public string WatchListName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_WATCHLIST_ELEMENT> TBL_WATCHLIST_ELEMENT { get; set; }
    }
}
